apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-example
spec:
  selector:
    matchLabels:
      app:  web-example
  template:
    metadata:
      labels:
        app:  web-example
    spec:
      containers:
        - name:  web-example
          image:  image-registry.openshift-image-registry.svc:5000/openshift/dotnet:latest
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
