kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nginx-route
spec:
  to:
    kind: Service
    name: nginx-svc
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
